version: '2'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app:rw
  auth:
    networks:
      - auth
    image: 'auth:latest'
    build:
      context: ./back/auth
    depends_on:
       - auth-db
       - broker
    container_name: bantads-auth
    ports:
      - "5000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./back/auth:/app
  auth-db:
    networks:
      - auth
    image: 'postgres:13.1-alpine'
    container_name: bantads-auth-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cliente:
    networks:
      - cliente
    image: 'cliente:latest'
    build:
      context: ./back/cliente
    depends_on:
       - cliente-db
    container_name: bantads-cliente
    ports:
      - "5001:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cliente-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  cliente-db:
    networks:
      - cliente
    image: 'postgres:13.1-alpine'
    container_name: bantads-cliente-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  gerente:
    networks:
      - gerente
    image: 'gerente:latest'
    build:
      context: ./back/gerente
    depends_on:
       - gerente-db
    container_name: bantads-gerente
    ports:
      - "5002:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gerente-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  gerente-db:
    networks:
      - gerente
    image: 'postgres:13.1-alpine'
    container_name: bantads-gerente-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  broker:
    networks:
      - auth
      - cliente
      - account
      - gerente
    container_name: bantads-broker
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
  account:
    image: 'account:latest'
    container_name: bantads-account
    networks:
      - gerente
    image: 'gerente:latest'
    build:
      context: ./back/gerente
    depends_on:
       - gerente-db
    container_name: bantads-gerente
    ports:
      - "5002:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gerente-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  gerente-db:
    networks:
      - gerente
    image: 'postgres:13.1-alpine'
    volumes:
      - ./bds/account/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
networks:
  auth:
    driver: bridge
  cliente:
    driver: bridge
  gerente:
    driver: bridge
  account:
    name: account
    driver: bridge