version: '2'

services:
  db:
    container_name: db_bantads_acc
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=accounts
    ports:
      - "5433:5432"
